### PR TITLE
738: Fixing account number format for VRP payments

### PR DESCRIPTION
**Pull request by frlaura-jianu**
Issue: https://github.com/secureapigateway/secureapigateway/issues/738
Description: Fixed account number format for VRP payments.

### CODE REVIEW

**Review by jorgesanchezperez — CHANGES_REQUESTED** [review]
This change affect all account format displayed in the components, and now doesn't display the short code where is expected, please fix the components using the `AccountNumberFormat` pipe together with `AccountSortCodeFormat` in these components where now only is displayed the account number.

Check the application `npm run serve.rcs.local` https://localhost:4201/dev/consent with no changes and with that change to identify the difference and the components where is necessary to be updated to add the short code too.

**Comment by frlaura-jianu** [comment]
> This change affect all account format displayed in the components, and now doesn't display the short code where is expected, please fix the components using the `AccountNumberFormat` pipe together with `AccountSortCodeFormat` in these components where now only is displayed the account number.
> 
> Check the application `npm run serve.rcs.local` https://localhost:4201/dev/consent with no changes and with that change to identify the difference and the components where is necessary to be updated to add the short code too.

Made the requested changes.

**Review by jorgesanchezperez — APPROVED** [review]
Nice Job!

**Comment by frlaura-jianu** [comment]
> Nice Job!

Thanks !

**Pull request merged**
